### ISSUE TITLE
希望更新上游文档

### ISSUE THREAD

**Issue by YDX-2147483647** [Scholar-Compass/Scholar-Compass-backend#2]
你好，我之前改了一下学校文档这两处，请问能否更新一下？如果没时间的话，我手动 PR 把更改同步到仓库也行。

https://github.com/Scholar-Compass/Scholar-Compass-backend/blob/7e7bed3391b8cb98fa655dbf5b43954ae43dc6aa/md_uni/%E5%8C%97%E4%BA%AC%E7%90%86%E5%B7%A5%E5%A4%A7%E5%AD%A6.md?plain=1#L49

https://github.com/Scholar-Compass/Scholar-Compass-backend/blob/7e7bed3391b8cb98fa655dbf5b43954ae43dc6aa/md_uni/%E4%B8%AD%E5%9B%BD%E7%A7%91%E5%AD%A6%E9%99%A2%E5%A4%A7%E5%AD%A6.md?plain=1#L75

**Comment by Astatine-213-Tian** [comment]
感谢提醒，已更新
https://github.com/Scholar-Compass/Scholar-Compass-backend/commit/9e4ea59789134818fe96ca495c8c1e9708ec291a
